### ISSUE TITLE
Ground truth for frame interpolation in inter4k

### ISSUE THREAD

**Issue by sramakintel** [alexandrosstergiou/Inter4K#1]
for video frame interpolation, i see downloading the data that they are .mp4 files at 60fps. Does this dataset provide the ground truth (example for 2x interpolation, we insert a new frame between every two frames)? Or do we need to make the ground truth ourselves from the .mp4 files ? If so how to use this dataset for benchmarking?

**Comment by alexandrosstergiou** [comment]
Hi @sramakintel,

The ground truth is generated by `resolution_changes.py`, which creates the different resolutions and frame rates. With that said, the possible frame and fps interpolations that can be performed are:

+ For frame resolutions:

| Rate | initial resolution | target resolution |
| :---: | :---: | :---:|
| 2x | 360p/nHD | 720p/HD |
| 2x | 540p/qHD | 1080p/FHD |
| 2x |  720p/HD | 1440p/2K/QHD |
| 2x | 1080p/FHD | 2160p/4K/UHD |
| 4x | 360p/nHD | 1440p/2K/QHD |
| 4x | 540p/qHD | 2160p/4K/UHD |

+ for frame rates:

| Rate | initial fps| target fps |
| :---: | :---: | :---:|
| 2x | 15 | 30 |
| 2x | 24 | 50 |
| 2x |  30 | 60 |
| 4x | 15 | 60 |

(and the subsequent combinations of the two tables for the join task of frame and fps interpolation).
