### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by altair199797** [alexandrosstergiou/Inter4K#3]
Hi,
are we allowed to use these videos, edit them and distribute them for scientific purposes?

**Comment by alexandrosstergiou** [comment]
Hi @altair199797 ,

Yes, you can use/edit the videos as well as re-distribute them by giving the appropriate reference to the source: either the paper or this repo. And also re-distribute under the same licensing.

Of course, as long as this is not done for commercial purposes.

You can have a look at more info about the license here: https://creativecommons.org/licenses/by-nc-sa/4.0/
